### ISSUE TITLE
No .xcodeproj file?

### ISSUE THREAD

**Issue by RenniePet** [Balancingrock/SwifterSockets#2]
This is presumably a dumb question (I'm very new to Swift and Xcode), but I can't find the .xcodeproj file in your project. Is this the way it's supposed to be?

**Comment by Swiftrien** [comment]
The short answer: Yes.

The longer answer: SwifterSockets is a SPM (Swift Package Manager) package.
If you need it in a project you have to build the framework for it. This can be easily done by the following command:

$ swift package generate-xcodeproj

In the top level directory of the project (where the Package.swift file resides)

Then open the generated xcode project, make sure that in the Build Settings for the target the Defines Module is set to “Yes”. And build the target.

Then import the framework by adding it to the “Embedded Binaries” in the project that needs SwifterSockets.  


Thanks for asking, since that made me realize I really need to put this info in the readme. And probably even include an xcode project to make the framework generation easier.
Look for that to appear later today.

Regards,
Rien

Site: http://balancingrock.nl
Blog: http://swiftrien.blogspot.com
Github: http://github.com/Balancingrock
Project: http://swiftfire.nl

**Comment by Balancingrock** [comment]
Added the xcode project for framework generation and updated the readme
